### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by syoung** [azawawi/atom-perl6-editor-tools#15]
Steps to reproduce:
1. Upgrading to version 0.9.16
2. Get red notification popup:

```
Uncaught TypeError: undefined is not a function
/home/syoung/.atom/packages/atom-perl6-editor-tools/lib/help-hyperclick.js:14
Show Stack Trace
The error was thrown from the atom-perl6-editor-tools package.
You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the atom-perl6-editor-tools package
```

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [atom-perl6-editor-tools](https://github.com/azawawi/atom-perl6-editor-tools) package, v0.9.16
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/syoung/.atom/packages/atom-perl6-editor-tools/lib/help-hyperclick.js:14

TypeError: undefined is not a function
    at /home/syoung/.atom/packages/atom-perl6-editor-tools/lib/help-hyperclick.js:14:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
 23x -4:55.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:50.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:46.5.0 editor:fold-all (atom-text-editor.editor.is-focused)
     -4:44.6.0 editor:unfold-all (atom-text-editor.editor.is-focused.hyperclick)
     -4:43.2.0 editor:fold-all (atom-text-editor.editor.is-focused.hyperclick)
     -4:41.5.0 editor:unfold-all (atom-text-editor.editor.is-focused.hyperclick)
  2x -4:40.2.0 editor:fold-all (atom-text-editor.editor.is-focused.hyperclick)
  5x -4:31.5.0 core:page-down (atom-text-editor.editor.is-focused)
  2x -4:20.9.0 core:page-up (atom-text-editor.editor.is-focused)
 11x -4:20.3.0 core:page-down (atom-text-editor.editor.is-focused)
  4x -4:17.7.0 core:page-up (atom-text-editor.editor.is-focused)
     -3:39.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:38.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:38.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:36.2.0 editor:unfold-current-row (atom-text-editor.editor.is-focused.hyperclick)
     -2:05.6.0 settings-view:open (atom-text-editor.editor.is-focused.hyperclick)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.perl6fe": [
        "p6",
        "pm",
        "pm6",
        "t"
      ]
    },
    "disabledPackages": [
      "language-perl",
      "language-xml",
      "language-xsl"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-macros, v0.5.2
atom-perl6-editor-tools, v0.9.16
auto-fold, v0.2.0
build, v0.54.1
fold-functions, v0.4.3
hyperclick, v0.0.35
language-perl6fe, v1.6.1
language-xlog, v0.0.0
linter, v1.11.3
open-recent, v5.0.0

# Dev
No dev packages
```

**Comment by azawawi** [comment]
Did it happen again after the upgrade?
