### ISSUE TITLE
Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by MadcapJake** [azawawi/atom-perl6-editor-tools#19]
I'm getting this on any file I throw at it (no `BEGIN` blocks in sight).

```
Error: Missing html/text field on Linter Response
    at /home/jrusso/.atom/packages/linter/lib/validate.coffee:40:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/home/jrusso/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (/home/jrusso/.atom/packages/linter/lib/message-registry.js:36:16)
    at /home/jrusso/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /home/jrusso/.atom/packages/linter/lib/linter-registry.js:66:26
```

**Comment by azawawi** [comment]
Greeting fellow stranger :+1: 

What's the version of linter on your atom? I recently saw an issue closed on their end.

**Comment by MadcapJake** [comment]
1.11.3, isn't that the latest?

**Comment by kmwallio** [comment]
It looks like:

``` coffeescript
if (output.stdout.endsWith("Syntax OK\n") && output.stderr == "") 
```

is failing.  On files that I'm seeing this, the stderr is empty, and Syntax OK is printed.  This makes the message empty.  Linter throws the error message when both text and html are empty.
